//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHSX2.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MHSX2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 【空き】 的當地語系化字串。
        /// </summary>
        internal static string BLANK_EQUIP_NAME {
            get {
                return ResourceManager.GetString("BLANK_EQUIP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dat 的當地語系化字串。
        /// </summary>
        internal static string DNAME_DAT {
            get {
                return ResourceManager.GetString("DNAME_DAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 favorite 的當地語系化字串。
        /// </summary>
        internal static string DNAME_FAVORITE {
            get {
                return ResourceManager.GetString("DNAME_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 history 的當地語系化字串。
        /// </summary>
        internal static string DNAME_HISTORY {
            get {
                return ResourceManager.GetString("DNAME_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 picture 的當地語系化字串。
        /// </summary>
        internal static string DNAME_PICT {
            get {
                return ResourceManager.GetString("DNAME_PICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 setting 的當地語系化字串。
        /// </summary>
        internal static string DNAME_SETTING {
            get {
                return ResourceManager.GetString("DNAME_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 eset 的當地語系化字串。
        /// </summary>
        internal static string EXTENSION_EQUIPSET {
            get {
                return ResourceManager.GetString("EXTENSION_EQUIPSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Classes.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_CLASSES {
            get {
                return ResourceManager.GetString("FNAME_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clothes.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_CLOTHES {
            get {
                return ResourceManager.GetString("FNAME_CLOTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dat.db 的當地語系化字串。
        /// </summary>
        internal static string FNAME_DAT_DB {
            get {
                return ResourceManager.GetString("FNAME_DAT_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Define.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_DEFINE {
            get {
                return ResourceManager.GetString("FNAME_DEFINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquipArm.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_EQUIPARM {
            get {
                return ResourceManager.GetString("FNAME_EQUIPARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquipBody.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_EQUIPBODY {
            get {
                return ResourceManager.GetString("FNAME_EQUIPBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquipHead.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_EQUIPHEAD {
            get {
                return ResourceManager.GetString("FNAME_EQUIPHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquipLeg.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_EQUIPLEG {
            get {
                return ResourceManager.GetString("FNAME_EQUIPLEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquipWst.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_EQUIPWST {
            get {
                return ResourceManager.GetString("FNAME_EQUIPWST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ignore.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_IGNORE {
            get {
                return ResourceManager.GetString("FNAME_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_ITEM {
            get {
                return ResourceManager.GetString("FNAME_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Jewel.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_JEWEL {
            get {
                return ResourceManager.GetString("FNAME_JEWEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 setting.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_SETTING {
            get {
                return ResourceManager.GetString("FNAME_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SkillBase.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_SKILLBASE {
            get {
                return ResourceManager.GetString("FNAME_SKILLBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SkillCuff.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_SKILLCUFF {
            get {
                return ResourceManager.GetString("FNAME_SKILLCUFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weapon.xml 的當地語系化字串。
        /// </summary>
        internal static string FNAME_WEAPON {
            get {
                return ResourceManager.GetString("FNAME_WEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://mhsx2.web.fc2.com 的當地語系化字串。
        /// </summary>
        internal static string URL_HOME_PAGE {
            get {
                return ResourceManager.GetString("URL_HOME_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 version 的當地語系化字串。
        /// </summary>
        internal static string VERSION_FILE_NAME {
            get {
                return ResourceManager.GetString("VERSION_FILE_NAME", resourceCulture);
            }
        }
    }
}
